# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['main.py'],
             binaries=[],
             datas=[],
             hiddenimports=[
                'websockets.legacy',
                'websockets.legacy.server',
                "auth.legacy",
                "basic_auth_protocol_factory.legacy.auth",
                "BasicAuthWebSocketServerProtocol.legacy.auth",
                "ClientConnection.client",
                "connect.legacy.client",
                "unix_connect.legacy.client",
                "WebSocketClientProtocol.legacy.client",
                "Headers.datastructures",
                "MultipleValuesError.datastructures",
                "WebSocketException.exceptions",
                "ConnectionClosed.exceptions",
                "ConnectionClosedError.exceptions",
                "ConnectionClosedOK.exceptions",
                "InvalidHandshake.exceptions",
                "SecurityError.exceptions",
                "InvalidMessage.exceptions",
                "InvalidHeader.exceptions",
                "InvalidHeaderFormat.exceptions",
                "InvalidHeaderValue.exceptions",
                "InvalidOrigin.exceptions",
                "InvalidUpgrade.exceptions",
                "InvalidStatusCode.exceptions",
                "NegotiationError.exceptions",
                "DuplicateParameter.exceptions",
                "InvalidParameterName.exceptions",
                "InvalidParameterValue.exceptions",
                "AbortHandshake.exceptions",
                "RedirectHandshake.exceptions",
                "InvalidState.exceptions",
                "InvalidURI.exceptions",
                "PayloadTooBig.exceptions",
                "ProtocolError.exceptions",
                "WebSocketProtocolError.exceptions",
                "protocol.legacy",
                "WebSocketCommonProtocol.legacy.protocol",
                "ServerConnection.server",
                "serve.legacy.server",
                "unix_serve.legacy.server",
                "WebSocketServerProtocol.legacy.server",
                "WebSocketServer.legacy.server",
                "Data.typing",
                "Origin.typing",
                "ExtensionHeader.typing",
                "ExtensionParameter.typing",
                "Subprotocol.typing"
             ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='microtonal-seaboard',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
